Ax 351 0.3
SportsToken/ax_dapp pull request #259
Opened 2022-02-28 22:31 UTC by Friendlygeckos

2022-03-06 03:42 UTC, ketonkss4 commented
Can you add screenshots for the UI changes?

2022-03-11 21:50 UTC, pearlson16 requested changes
Looks like this is not caught up with develop and need the flutter analyze changed that are on develop

2022-03-13 01:14 UTC, pearlson16 approved these changes

2022-03-15 01:35 UTC, ketonkss4 approved these changes

2022-03-15 01:57 UTC, user2745 approved these changes

2022-03-16 01:26 UTC, merged