Ax 381 need separate token icons for long short athlete tokens
SportsToken/ax_dapp pull request #271
Opened 2022-03-15 21:10 UTC by bekchanovj

# Description
Updated the list of athlete tokens: added long and short icons for each APT. Added long and short token addresses to the map of addresses. 

Fixes Jira Ticket # 381

## Type of change
Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Is this a UI Change? Yes
![Screenshot 2022-03-15 170156](https://user-images.githubusercontent.com/59264759/158472003-c76e0d23-85e8-4e26-a56e-b0c3d1507879.jpg)

# How Has This Been Tested?
This is mostly a UI change and was tested while running the application and finding the list of the tokens on the Trade page. 

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have assigned 2 reviewers to check my work
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-16 20:15 UTC, user2745 approved these changes

2022-03-18 17:09 UTC, pearlson16 requested changes
The player icons don't populate on the mobile version. This was fixed on the last trade page commit Ax 351 0.3 - Make Trade Page Responsive #259, seems like those changed got reverted why?

2022-03-18 18:57 UTC, pearlson16 approved these changes

2022-03-21 11:26 UTC, ketonkss4 approved these changes

2022-03-21 15:33 UTC, merged