Ax 428 add baseball endpoints
SportsToken/ax_dapp pull request #289
Opened 2022-04-03 22:50 UTC by mretana1999

# Description
Implemented API calls with Retrofit library which will replace AthleteAPI.dart (which previously used http library). Added API calls for NFL and MLB separately. Created NFLAthlete and MLBAthlete model classes that will contain the JSON objects retrieved from the API. Finally, I also added API call with MLB athlete's ids.

Fixes Jira Ticket #428

## Type of change
Please delete options that are not relevant.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Application was run using chrome browser in debugging mode.

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have assigned 2 reviewers to check my work
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-04 21:55 UTC, ketonkss4 requested changes
This ticket is about adding MLB api endpoints to the project and nothing else. Making NFL related tickets on a ticket about MLB will cause unnecessary confusion. Stash all changes related to refactoring the NFL data calls all except for the Rename as that was relevant to MLB so we could differentiate the two data sources.

2022-04-04 21:55 UTC, ketonkss4 commented on lib/pages/DesktopScout.dart
> +        {print("First NFL player retrieved: ${response.first.name}")});
This is out of scope for this ticket we can handle Refactoring the way we call NFL endpoints later

2022-04-04 21:55 UTC, ketonkss4 commented on lib/pages/DesktopTrade.dart
> +    print("This is token list: ${TokenList.tokenList}");
This looks like a debug print statement we should remove it if its not needed

2022-04-04 21:55 UTC, ketonkss4 commented on lib/pages/ExplorePage.dart
> +                                                      ]
Why were these changes made? They dont seem relevant to the ticket

2022-04-04 21:55 UTC, ketonkss4 commented on lib/pages/LandingPage.dart
> +                future: NFLRepo(NFLAthleteAPI(Dio())).getPlayersById(),
This is not the ticket to make this change

2022-04-04 21:55 UTC, ketonkss4 commented on lib/repositories/MlbRepo.dart
> +  static final int vladimirGuerreroId = 10007501;
Create a datasource you can pass in to provide these values.

2022-04-04 21:55 UTC, ketonkss4 commented on lib/repositories/NFLRepo.dart
> +}
Lets save this refactoring for a NFL specific ticket

2022-04-04 21:55 UTC, ketonkss4 commented on lib/service/TokenList.dart
> +    }).toList(),
why are these changes being made on this ticket?

2022-04-04 21:55 UTC, ketonkss4 commented on lib/service/athleteModels/NFLAthlete.dart
> +class NFLAthlete {
Stash these changes and apply them for a NFL specific refactoring ticket

2022-04-04 21:55 UTC, ketonkss4 commented on lib/service/athlete_api/NFLAthleteAPI.dart
> +}
Stash these changes and introduce them when we have an NFL refactoring ticket

2022-04-04 23:40 UTC, ketonkss4 approved these changes

2022-04-05 20:35 UTC, pearlson16 approved these changes

2022-04-05 20:35 UTC, merged