Ax 425 trade page swap widget functionality
SportsToken/ax_dapp pull request #301
Opened 2022-04-12 19:34 UTC by mretana1999

# Description
Added balance widget to swap page which shows the user their current balance for the selected tokens. Fixed input boxes so that they expand when user enters larger numbers. Fixed number of accepted decimals to 5 on trade page.

Fixes Jira Ticket #425 

## Type of change
Please delete options that are not relevant.
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# Is this a UI Change? If so please include screenshot of before and after states below

## Before: 
![image](https://user-images.githubusercontent.com/70818506/163039652-efecd016-0485-4905-ba05-91ac6ad698c9.png)

## After:
![image](https://user-images.githubusercontent.com/70818506/163039715-30c9df6c-94ab-4f1e-8dd3-9dbb94248731.png)

# How Has This Been Tested?
Tested by running web-server on chrome in debugging mode.

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have assigned 2 reviewers to check my work
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-13 14:22 UTC, Friendlygeckos requested changes

2022-04-13 14:22 UTC, Friendlygeckos commented on lib/service/Dialog.dart
> +                                image: AssetImage("assets/images/apt.png"),
change this to apt_noninverted.png

2022-04-13 14:22 UTC, Friendlygeckos commented on lib/service/Dialog.dart
> +                                image: AssetImage("assets/images/apt.png"),
Also change this to apt_noninverted.png

2022-04-13 18:41 UTC, Friendlygeckos approved these changes

2022-04-14 22:12 UTC, pearlson16 approved these changes

2022-04-16 02:29 UTC, merged