AX-492 SwapInfo usecase and model
SportsToken/ax_dapp pull request #331
Opened 2022-05-03 03:14 UTC by bekchanovj

# Description
Added SwapInfo usecase and model. 

Fixes Jira Ticket # 
492
https://athletex.atlassian.net/browse/AX-492?atlOrigin=eyJpIjoiZWRhOTI0Nzg2MWE4NDQ4NjhjMWM3N2EwZDQwNGY3ODAiLCJwIjoiaiJ9

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have assigned 2 reviewers to check my work
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-03 03:21 UTC, ketonkss4 requested changes
Please add a test for GetSwapInfoUseCase

2022-05-03 03:21 UTC, ketonkss4 commented on lib/dialogs/buy/usecases/GetSwapInfoUseCase.dart
> +const String _no_swap_info_error_msg = "No buy info found";
I think you need to update this error message to be specifically for swap?

2022-05-04 00:13 UTC, ketonkss4 approved these changes

2022-05-05 00:09 UTC, pearlson16 approved these changes

2022-05-05 00:21 UTC, merged