Ax 478 trade page connect trade page to sub graph data provided from trade page bloc
SportsToken/ax_dapp pull request #336
Opened 2022-05-07 18:01 UTC by mretana1999

# Description
Deleted previous trade page file, added a new one that loads information from TradePageBloc.

Fixes Jira Ticket #478

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Is this a UI Change? If so please include screenshot of before and after states below

## Before:
![image](https://user-images.githubusercontent.com/70818506/167266186-425582b1-ee9c-45e4-8aa8-7e2c00706f06.png)

## After:
![image](https://user-images.githubusercontent.com/70818506/167266148-2fba5723-787c-4434-80b9-2f3e03d2401a.png)

# How Has This Been Tested?
Ran using chrome web-server in debugging mode.

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have assigned 2 reviewers to check my work
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-08 21:21 UTC, ketonkss4 requested changes

2022-05-08 21:21 UTC, ketonkss4 commented on lib/pages/trade/bloc/TradePageBloc.dart
> +  void _mapRefreshEventToState(
Lets add a quick test here

2022-05-09 14:30 UTC, mretana1999 commented on lib/pages/V1App.dart
> +                            launchUrl(Uri.parse(
launch is deprecated, launchUrl is not

2022-05-09 20:52 UTC, ketonkss4 approved these changes

2022-05-09 20:53 UTC, pearlson16 approved these changes

2022-05-09 21:10 UTC, merged