feat: Setting up Sell dialog BloC
SportsToken/ax_dapp pull request #338
Opened 2022-05-09 06:35 UTC by bekchanovj

refactor: Changing event names

refactor: Changing event methods names

# Description
//Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes Jira Ticket # 

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Is this a UI Change? If so please include screenshot of before and after states below

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have assigned 2 reviewers to check my work
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-09 19:18 UTC, ketonkss4 requested changes

2022-05-09 19:18 UTC, ketonkss4 commented on lib/service/BlockchainModels/AptSellInfo.dart
> +class AptSellInfo {
This is nearly the same thing as AptBuyInfo, lets consolidate the models to AptTransactionInfo or something along those lines

2022-05-09 19:18 UTC, ketonkss4 commented on lib/dialogs/sell/usecases/GetAPTSellInfoUseCase.dart
> +class GetAPTSellInfoUseCase {
Looks very similar to GetBuyInfoUseCase... Perhaps we can consolidate the two? Buy is a swap between the targetApt and Ax so maybe the GetBuyInfoUseCase should just call this with a hardcoded tokenFrom value

2022-05-09 19:18 UTC, ketonkss4 commented on lib/dialogs/sell/bloc/SellDialogBloc.dart
> +        final buyInfo = response.getLeft().toNullable()!.aptSellInfo;
The copy is showing here with your variable name choice

2022-05-10 18:53 UTC, pearlson16 submitted a review, later dismissed

2022-05-10 19:16 UTC, mretana1999 commented on lib/dialogs/sell/bloc/SellDialogBloc.dart
> +      final maxInput = await wallet.getTotalAxBalance();
should this fetch the current APT balance?

2022-05-10 19:38 UTC, mretana1999 approved these changes

2022-05-10 20:06 UTC, pearlson16 approved these changes

2022-05-10 21:50 UTC, merged