Ax 419 pool page update the details w the names stats of the tokens selected
SportsToken/ax_dapp pull request #353
Opened 2022-05-16 16:18 UTC by mretana1999

# Description
Removed pool confirm dialog from AddLiquidity.dart and moved you receive widget inside this page. Moved approve button into AddLiquidity page and modified the layout of other widgets such as balance.

Fixes Jira Ticket #419

## Type of change
Please delete options that are not relevant.
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Is this a UI Change? If so please include screenshot of before and after states below

## Before:
![image](https://user-images.githubusercontent.com/70818506/168638061-45d7c92a-a1d6-4e3d-b7d5-ac1ef96e58b5.png)

## After:
![image](https://user-images.githubusercontent.com/70818506/168638028-bbd9a032-191f-481c-9564-b97e1c4e057a.png)

# How Has This Been Tested?
Application ran using chrome web-server in debugging mode

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have assigned 2 reviewers to check my work
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-16 19:15 UTC, robkizzle requested changes
Move the note into tooltip above "You will receive"

2022-05-16 22:50 UTC, ketonkss4 approved these changes

2022-05-17 01:32 UTC, Friendlygeckos requested changes

2022-05-17 01:32 UTC, Friendlygeckos commented on lib/pages/pool/AddLiquidity/AddLiquidity.dart
> +                    "*Add liquidity to earn 0.25% of all trades on this pair proportional to your share of the pool and receive LP tokens.",
Should we have the asterisk here at the beginning? I looked at other tooltip examples and they do not contain a special character like that.

2022-05-17 16:12 UTC, robkizzle approved these changes

2022-05-17 17:11 UTC, Friendlygeckos approved these changes

2022-05-17 17:14 UTC, merged