Ax 548 pool page my liquidity fix search bar on my liquidity
SportsToken/ax_dapp pull request #370
Opened 2022-05-25 18:50 UTC by mretana1999

# Description
Fixed search bar functionality on MyLiquidity page.

Fixes Jira Ticket #548

## Type of change
Please delete options that are not relevant.
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Is this a UI Change? If so please include screenshot of before and after states below

## Before:
![image](https://user-images.githubusercontent.com/70818506/170345817-2caa6f0c-5e53-429d-955b-6bc116c3c5fc.png)

## After:
![image](https://user-images.githubusercontent.com/70818506/170345638-c24786ea-5c42-4bd7-be0a-6c25bfdd7db4.png)
![image](https://user-images.githubusercontent.com/70818506/170345709-4b33b667-db1b-47a1-ae6c-17ea1f38f35e.png)

# How Has This Been Tested?
Application was run using Chrome in debugging mode and connecting my wallet to check my liquidity positions.

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have assigned 2 reviewers to check my work
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-25 20:06 UTC, bekchanovj commented on lib/pages/pool/MyLiqudity/MyLiquidity.dart
> +                    bloc.add(SearchBarInputEvent(searchBarInput: value));
Needs a check here, trim the input or check if the input contains characters. Just good practice. Otherwise, it shows an empty list on whitespaces.

2022-05-25 20:08 UTC, bekchanovj requested changes

2022-05-25 20:08 UTC, bekchanovj commented on lib/pages/pool/MyLiqudity/MyLiquidity.dart
> +    Widget createMyLiquiditySearchBar(
a

2022-05-26 18:56 UTC, Friendlygeckos approved these changes

2022-05-26 19:22 UTC, bekchanovj approved these changes

2022-05-26 22:23 UTC, merged