[Pool Page - My Liquidity] - Default set the Remove liquidity slider …
SportsToken/ax_dapp pull request #371
Opened 2022-05-25 19:18 UTC by pearlson16

…to 0%

# Description
when user clicks cancel slider to zero so it defaults to zero when selecting another pool

Fixes Jira Ticket # https://athletex.atlassian.net/browse/AX-546

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have assigned 2 reviewers to check my work
- [x] My changes generate no new warnings

2022-05-25 20:06 UTC, mretana1999 approved these changes

2022-05-25 20:12 UTC, bekchanovj requested changes

2022-05-25 20:12 UTC, bekchanovj commented on lib/pages/pool/MyLiqudity/MyLiquidity.dart
> +                                            value = 0;
We need to update Pool Controller as well here. You can reference what I wrote on "value" change.

2022-05-27 18:47 UTC, bekchanovj approved these changes

2022-05-27 19:02 UTC, merged