Ax 524 0.2
SportsToken/ax_dapp pull request #416
Opened 2022-06-18 14:50 UTC by jayesh2408

# Description
Fixed athlete page according to the ticket which was fixing to MP:BV value text , hiding some text etc.

Fixes Jira Ticket # 

## Type of change
Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Is this a UI Change? If so please include screenshot of before and after states below
yes.

# How Has This Been Tested?
yes

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have assigned 2 reviewers to check my work

- [ ] My changes generate no new warnings

- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-18 15:48 UTC, Friendlygeckos requested changes
- You still need to fix the MP:BV ratios on the athlete page. Right now they are still showing the same values for all the athletes.
- You also still need to remove the all time high book value and market price. Right now they are currently present on the athlete page

2022-06-18 15:48 UTC, Friendlygeckos commented on lib/pages/AthletePage.dart
> +                                            style: textStyle(greyTextColor.withOpacity(0), 14,
why do we have `.withOpacity(0)`? I do not see a difference in the text

2022-06-18 15:48 UTC, Friendlygeckos commented on lib/pages/AthletePage.dart
> +
I do not think it is necessary to have the extra spacing here

2022-06-18 15:48 UTC, Friendlygeckos commented on lib/pages/AthletePage.dart
> +                                                  Visibility(
Why are we using a visibility widget if we are not going to toggle the visibility at all?

2022-06-18 15:48 UTC, Friendlygeckos commented on lib/pages/AthletePage.dart
> +                                                          greyTextColor.withOpacity(1),
Why do we have `.withOpacity(1)`? I do not see a difference in the text

2022-06-18 21:26 UTC, Friendlygeckos requested changes

2022-06-18 21:26 UTC, Friendlygeckos commented on lib/pages/AthletePage.dart
> +
Remove the space

2022-06-18 21:26 UTC, Friendlygeckos commented on lib/pages/AthletePage.dart
> +
Remove the space here aswell

2022-06-25 18:47 UTC, user2745 approved these changes

2022-06-26 17:27 UTC, mretana1999 approved these changes

2022-06-26 17:50 UTC, Friendlygeckos approved these changes

2022-06-26 17:50 UTC, merged