mint dialog overflow issue fixed
SportsToken/ax_dapp pull request #526
Opened 2022-08-15 01:25 UTC by jayesh2408

# Description
Fixed overflow issue on mint dialog.

Fixes Jira Ticket # 
AX-784
## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Is this a UI Change? If so please include screenshot of before and after states below
yes
after
![picture](https://user-images.githubusercontent.com/54597975/184562679-80637a5d-de46-47a9-9547-17a11403e60b.JPG)

# How Has This Been Tested?
yes

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have assigned 2 reviewers to check my work
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-08-16 14:32 UTC, durduman commented
<img width="422" alt="Screenshot 2022-08-16 at 17 31 49" src="https://user-images.githubusercontent.com/1089865/184905849-b7b21974-9b46-41f5-978e-f1595415ab43.png">

2022-08-16 14:33 UTC, durduman requested changes
Please see attached image. Only part of the problem has been addressed.

2022-08-21 21:10 UTC, jayesh2408 commented
@durduman fixed

2022-08-23 18:48 UTC, durduman approved these changes

2022-08-23 18:53 UTC, Friendlygeckos approved these changes

2022-08-23 18:54 UTC, pearlson16 approved these changes

2022-08-23 18:54 UTC, merged