Ax 871 add checks to the frontend for displaying buttons
SportsToken/ax_dapp pull request #553
Opened 2022-08-25 21:04 UTC by MichaelFrank0317

# Description
Handle checks to the frontend for displaying buttons on mint, liquidity and trade

Fixes Jira Ticket # 871
https://athletex.atlassian.net/browse/AX-871

## Type of change
Please delete options that are not relevant.
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Is this a UI Change? If so please include screenshot of before and after states below
![image](https://user-images.githubusercontent.com/98486430/186768143-acb9bf22-7096-47ea-b2ee-30e845cecb51.png)
![image](https://user-images.githubusercontent.com/98486430/186768311-0b0f9821-f0ab-4019-9fa6-02842c5d40f8.png)
![image](https://user-images.githubusercontent.com/98486430/186768417-916f5f77-f5b6-47d7-9d1d-cac51e9b1ca9.png)
![image](https://user-images.githubusercontent.com/98486430/186768525-7ff16911-688a-4ff6-88eb-b05843e32a4d.png)
![image](https://user-images.githubusercontent.com/98486430/186768575-100c70a1-3896-47b3-ab36-a309f5295c2b.png)

# How Has This Been Tested?
This has been tested on the UI.

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have assigned 2 reviewers to check my work
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-25 21:27 UTC, Friendlygeckos requested changes
please grey out the button for the mint and add liquidity buttons. Look at the example for the trade page

2022-08-25 21:27 UTC, Friendlygeckos commented on lib/dialogs/mint/bloc/mint_dialog_event.dart
> +  final double axAmount;
@override
  List<Object?> get props => [axAmount];

2022-08-25 21:27 UTC, Friendlygeckos commented on lib/pages/athlete/components/athlete_mint_approve_button.dart
> +          if (iswaitingApproval) return;
what is going on over here? Why do we need it?

2022-08-25 21:27 UTC, Friendlygeckos commented on lib/pages/scout/desktop_scout.dart
> +                        return;
why are we returning here?

2022-08-25 21:27 UTC, Friendlygeckos commented on lib/pages/scout/dialogs/athlete_page_dialogs.dart
> +export '../../../dialogs/mint/mint_dialog.dart';
provide the absolute path

2022-09-05 23:08 UTC, ketonkss4 requested changes
Rebase!~

2022-09-07 12:38 UTC, closed without merging