fix: balance error on USDC
SportsToken/ax_dapp pull request #648
Opened 2022-09-21 14:29 UTC by MichaelFrank0317

# Description
Fix the balance error on USDC token on the trade

Fixes Jira Ticket # 777
https://athletex.atlassian.net/browse/AX-777

## Type of change
Please delete options that are not relevant.
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Is this a UI Change? If so please include screenshot of before and after states below
NO

# How Has This Been Tested?
This has been tested on the it's branch.

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have assigned 2 reviewers to check my work
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-21 17:39 UTC, Friendlygeckos requested changes

2022-09-21 17:39 UTC, Friendlygeckos commented on lib/pages/trade/bloc/trade_page_bloc.dart
> +      print(state.tokenFrom.address);
remove print statements

2022-09-21 17:39 UTC, Friendlygeckos commented on lib/pages/trade/bloc/trade_page_bloc.dart
> +      print(tokenFromBalance);
remove print statements

2022-09-21 18:08 UTC, MichaelFrank0317 commented on lib/pages/trade/bloc/trade_page_bloc.dart
> +      print(state.tokenFrom.address);
remove

2022-09-21 18:30 UTC, Friendlygeckos approved these changes

2022-09-22 17:01 UTC, pearlson16 approved these changes

2022-09-22 17:12 UTC, merged