Fix/ax 650 routing side
SportsToken/ax_dapp pull request #722
Opened 2022-11-09 19:16 UTC by alexblackwell1

# Description
//Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes Jira Ticket # 

## Type of change
Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

# Is this a UI Change? If so please include screenshot of before and after states below

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have assigned 2 reviewers to check my work
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-11-09 22:05 UTC, Friendlygeckos requested changes

2022-11-09 22:53 UTC, alexblackwell1 commented on lib/service/global.dart
> +  }
Each page calls this method in the scaffold

2022-11-09 22:55 UTC, alexblackwell1 commented on lib/app/view/app_routing.dart
> +        },
I don't believe that the redirect actually returns null... it only executes if one of the conditions are met (and we don't want it redirecting to a specific page every time any link is pressed)

2022-11-10 21:09 UTC, Friendlygeckos approved these changes

2022-11-10 21:10 UTC, merged